name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install "black[jupyter]"  # Install Jupyter support for Black

    - name: Run Black
      run: |
        black .  # Allow Black to automatically reformat files

    - name: Run isort
      run: |
        isort --check-only .

    - name: Run Pylint
      run: |
        pylint src tests

    - name: Run tests with coverage
      run: |
        pytest --cov=src tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
