name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image with System Dependencies
      run: |
        docker build --build-arg PIP_UPGRADE=true -t local-llm-alignment-template:latest -f deployment/Dockerfile .

    - name: Run Docker Container Locally
      run: |
        docker run -d -p 8000:8000 --name llm-container local-llm-alignment-template:latest
